import { Prisma, PrismaClient } from '@prisma/client';
import { DdlCatalog, loadDdlCatalog, orderByDependency } from './schema-ddl';

/**
 * schema-drift.ts — runtime schema drift detection and additive repair
 * =============================================================================
 *
 * THE PROBLEM THIS SOLVES
 * -----------------------
 * ALUMFAB POS ships a template `pos.db` and copies it to
 * `%APPDATA%\ALUMFAB-POS\database\pos.db` on first launch — but only when the
 * file is missing. Every launch after that, the runtime database is whatever
 * the shop already had. Add a column to `schema.prisma`, run `db push` on the
 * dev box, ship the build, and the shop's database still has the old shape.
 *
 * Prisma then fails at the worst possible moment. It is not just writes: after
 * `product.update()` Prisma reads the row back with an explicit column list, so
 * a query that never mentions the new column still throws
 *
 *     P2022: The column `costPricePaise` does not exist in the current database
 *
 * mid-transaction, and the whole bulk import rolls back. That is exactly the
 * ODS ingestion failure this module exists to prevent.
 *
 * THE APPROACH
 * ------------
 * `Prisma.dmmf` is the datamodel embedded in the generated client. It is
 * regenerated by `prisma generate` on every build, so it cannot fall out of
 * sync with `schema.prisma` the way a hand-maintained migration list can. We
 * compare it against SQLite's `PRAGMA table_info` and classify each difference:
 *
 *   ADDITIVE  — something we can create losslessly: a missing column via
 *               ALTER TABLE, or a missing table via the DDL recorded in
 *               prisma/migrations. Repaired automatically, after a backup.
 *   BLOCKING  — a required column with no usable default, a type change, or a
 *               missing table we have no recorded DDL for. Never guessed at;
 *               the app refuses to start and tells the technician what to run.
 *   INFO      — a column in the database that the schema no longer knows
 *               about. Harmless: Prisma names its columns explicitly.
 *
 * MISSING TABLES
 * --------------
 * A CREATE TABLE needs exact column order, constraints, defaults and every
 * foreign key clause with the right ON DELETE / ON UPDATE action. Deriving that
 * from the datamodel means re-implementing Prisma's SQLite DDL generator, so
 * this module does not try. It reads the statements Prisma already wrote to
 * prisma/migrations (see schema-ddl.ts) and replays them verbatim. If the
 * catalog is unavailable — a partial checkout, or a build that forgot to ship
 * the resource — missing tables stay BLOCKING.
 *
 * Deliberately NOT handled: dropping columns, renaming, narrowing types. Those
 * need a real migration with a data plan, not a guess made at 8am while a
 * queue forms at the till.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type DriftSeverity = 'additive' | 'blocking' | 'info';

export interface DriftItem {
  severity: DriftSeverity;
  table: string;
  column?: string;
  kind:
    | 'missing-column'
    | 'missing-table'
    | 'type-mismatch'
    | 'extra-column'
    | 'missing-unique-index';
  detail: string;
  /** SQL that fixes this item. Only ever populated for `additive`. */
  sql?: string[];
}

export interface DriftReport {
  ok: boolean;
  /** True when every item is additive or info — safe to auto-repair. */
  repairable: boolean;
  items: DriftItem[];
  additive: DriftItem[];
  blocking: DriftItem[];
  /**
   * Flat, ordered list of statements that repairs all additive drift.
   * Tables are created before the columns of already-existing tables are
   * altered, and referenced tables before their dependents.
   */
  repairSql: string[];
  /** Where the recorded DDL came from, or null when no catalog was found. */
  ddlSource: string | null;
}

export interface AnalyseOptions {
  /** `app.getAppPath()` — lets the catalog resolve in a dev checkout. */
  appPath?: string;
  /** `process.resourcesPath` — lets it resolve in a packaged build. */
  resourcesPath?: string;
  /** Pre-loaded catalog, mainly for tests. */
  catalog?: DdlCatalog;
}

interface ExpectedColumn {
  name: string;
  /** SQLite column type Prisma would have used. */
  sqliteType: string;
  required: boolean;
  isUnique: boolean;
  isId: boolean;
  /** Literal SQL for DEFAULT, or null when the field has no usable default. */
  defaultSql: string | null;
  isUpdatedAt: boolean;
}

// ---------------------------------------------------------------------------
// Prisma scalar -> SQLite storage type
// ---------------------------------------------------------------------------
// Mirrors the mapping the Prisma SQLite connector emits in its migrations.
const SQLITE_TYPE: Record<string, string> = {
  String: 'TEXT',
  Boolean: 'BOOLEAN',
  Int: 'INTEGER',
  BigInt: 'BIGINT',
  Float: 'REAL',
  Decimal: 'DECIMAL',
  DateTime: 'DATETIME',
  Bytes: 'BLOB',
  Json: 'JSONB'
};

/**
 * SQLite is loosely typed and reports whatever text was in the CREATE TABLE
 * statement, so comparisons must be forgiving. These are treated as the same
 * storage class.
 */
const TYPE_ALIASES: Record<string, string> = {
  TEXT: 'TEXT',
  CLOB: 'TEXT',
  VARCHAR: 'TEXT',
  CHARACTER: 'TEXT',
  INTEGER: 'INTEGER',
  INT: 'INTEGER',
  BIGINT: 'INTEGER',
  BOOLEAN: 'INTEGER',
  TINYINT: 'INTEGER',
  REAL: 'REAL',
  DOUBLE: 'REAL',
  FLOAT: 'REAL',
  NUMERIC: 'REAL',
  DECIMAL: 'REAL',
  DATETIME: 'DATETIME',
  DATE: 'DATETIME',
  TIMESTAMP: 'DATETIME',
  BLOB: 'BLOB',
  JSONB: 'TEXT',
  JSON: 'TEXT'
};

function normaliseType(raw: string): string {
  const base = (raw || '').toUpperCase().replace(/\(.*\)$/, '').trim();
  return TYPE_ALIASES[base] ?? base;
}

// ---------------------------------------------------------------------------
// Default value rendering
// ---------------------------------------------------------------------------

/**
 * Render a DMMF default as a SQL literal usable in ALTER TABLE ADD COLUMN.
 * Returns null when the default cannot be expressed as a column default —
 * `cuid()`, `uuid()` and `autoincrement()` are generated by Prisma or by the
 * table definition, not by a DEFAULT clause.
 */
function renderDefault(field: Prisma.DMMF.Field): string | null {
  if (!field.hasDefaultValue) return null;
  const def = field.default as unknown;

  // Function defaults: { name: 'now', args: [] }
  if (def && typeof def === 'object' && 'name' in (def as Record<string, unknown>)) {
    const fnName = (def as { name: string }).name;
    if (fnName === 'now') return 'CURRENT_TIMESTAMP';
    // cuid / uuid / autoincrement / dbgenerated cannot be a column default.
    return null;
  }

  switch (typeof def) {
    case 'number':
      return String(def);
    case 'boolean':
      return def ? 'true' : 'false';
    case 'string':
      // Covers String defaults and enum members (stored as TEXT in SQLite).
      return `'${def.replace(/'/g, "''")}'`;
    default:
      return null;
  }
}

// ---------------------------------------------------------------------------
// Expected shape, derived from the generated client
// ---------------------------------------------------------------------------

function expectedTables(): Map<string, ExpectedColumn[]> {
  const tables = new Map<string, ExpectedColumn[]>();

  for (const model of Prisma.dmmf.datamodel.models) {
    const tableName = model.dbName || model.name;
    const columns: ExpectedColumn[] = [];

    for (const field of model.fields) {
      // Relation fields are not columns. The foreign key scalar (e.g.
      // `categoryId`) is a separate scalar field and is picked up below.
      if (field.kind === 'object') continue;
      if (field.isList) continue;

      const sqliteType = field.kind === 'enum' ? 'TEXT' : SQLITE_TYPE[field.type] ?? 'TEXT';

      columns.push({
        name: field.dbName || field.name,
        sqliteType,
        required: field.isRequired,
        isUnique: Boolean(field.isUnique),
        isId: Boolean(field.isId),
        defaultSql: renderDefault(field),
        isUpdatedAt: Boolean(field.isUpdatedAt)
      });
    }

    tables.set(tableName, columns);
  }

  return tables;
}

// ---------------------------------------------------------------------------
// Live database introspection
// ---------------------------------------------------------------------------

interface PragmaColumn {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

async function liveTables(client: PrismaClient): Promise<Set<string>> {
  const rows = await client.$queryRawUnsafe<{ name: string }[]>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
  );
  return new Set(rows.map((r) => r.name));
}

async function liveColumns(client: PrismaClient, table: string): Promise<PragmaColumn[]> {
  // PRAGMA does not accept bound parameters; the table name comes from our own
  // DMMF-derived list, never from user input.
  return client.$queryRawUnsafe<PragmaColumn[]>(`PRAGMA table_info("${table}")`);
}

// ---------------------------------------------------------------------------
// Analysis
// ---------------------------------------------------------------------------

/**
 * Compare the connected database against the generated Prisma datamodel.
 *
 * Read-only: this never modifies the database.
 */
export async function analyseDrift(
  client: PrismaClient,
  options: AnalyseOptions = {}
): Promise<DriftReport> {
  const items: DriftItem[] = [];
  const expected = expectedTables();
  const present = await liveTables(client);

  const catalog = options.catalog ?? loadDdlCatalog(options.appPath, options.resourcesPath);

  // Missing tables are collected first so they can be emitted ahead of every
  // ALTER, and ordered so a referenced table exists before its dependents.
  const missingTables: string[] = [];

  for (const [table, columns] of expected) {
    if (!present.has(table)) {
      const ddl = catalog.tables.get(table);

      if (!ddl) {
        items.push({
          severity: 'blocking',
          table,
          kind: 'missing-table',
          detail:
            `Table "${table}" is missing and no recorded DDL was found for it. ` +
            (catalog.root
              ? `The migration history at ${catalog.root} does not create this table — it was ` +
                `probably added with \`db push\` instead of a migration.`
              : `No migrations directory was found. In a packaged build this means the ` +
                `prisma/migrations resource was not shipped; see electron-builder.yml.`)
        });
        continue;
      }

      missingTables.push(table);
      items.push({
        severity: 'additive',
        table,
        kind: 'missing-table',
        detail:
          `Table "${table}" is missing. Will be created from the DDL recorded in ` +
          `migration ${ddl.source}${ddl.indexSql.length ? ` (plus ${ddl.indexSql.length} index(es))` : ''}.`,
        // SQL is attached after ordering, below.
        sql: []
      });
      continue;
    }

    const live = await liveColumns(client, table);
    const liveByName = new Map(live.map((c) => [c.name, c]));

    // ---- Columns the schema expects but the database lacks ---------------
    for (const col of columns) {
      const actual = liveByName.get(col.name);

      if (!actual) {
        const canAdd = !col.required || col.defaultSql !== null || col.isUpdatedAt;

        if (!canAdd) {
          items.push({
            severity: 'blocking',
            table,
            column: col.name,
            kind: 'missing-column',
            detail:
              `Column "${table}"."${col.name}" (${col.sqliteType}) is required and has no ` +
              `default, so SQLite cannot add it to a table that already holds rows. ` +
              `This needs a migration that decides what value existing rows should get.`
          });
          continue;
        }

        // SQLite's ALTER TABLE ADD COLUMN requires a non-NULL default for any
        // NOT NULL column. @updatedAt fields have no schema-level default, but
        // CURRENT_TIMESTAMP is a correct starting value — Prisma overwrites it
        // on the next write.
        const defaultSql = col.defaultSql ?? (col.isUpdatedAt ? 'CURRENT_TIMESTAMP' : null);
        const nullability = col.required ? ` NOT NULL DEFAULT ${defaultSql}` : defaultSql ? ` DEFAULT ${defaultSql}` : '';

        const sql = [`ALTER TABLE "${table}" ADD COLUMN "${col.name}" ${col.sqliteType}${nullability}`];

        // UNIQUE cannot be declared in ADD COLUMN; add the index separately.
        if (col.isUnique) {
          sql.push(`CREATE UNIQUE INDEX IF NOT EXISTS "${table}_${col.name}_key" ON "${table}"("${col.name}")`);
        }

        items.push({
          severity: 'additive',
          table,
          column: col.name,
          kind: 'missing-column',
          detail:
            `Column "${table}"."${col.name}" ${col.sqliteType}` +
            `${col.required ? ' NOT NULL' : ''}${defaultSql ? ` DEFAULT ${defaultSql}` : ''} is missing.`,
          sql
        });
        continue;
      }

      // ---- Type comparison ------------------------------------------------
      const wanted = normaliseType(col.sqliteType);
      const found = normaliseType(actual.type);
      if (wanted !== found) {
        items.push({
          severity: 'blocking',
          table,
          column: col.name,
          kind: 'type-mismatch',
          detail:
            `Column "${table}"."${col.name}" is ${actual.type} in the database but the schema ` +
            `expects ${col.sqliteType}. Changing a column type in SQLite means rebuilding the ` +
            `table; that needs a migration with a data-conversion plan.`
        });
      }
    }

    // ---- Columns the database has but the schema dropped -----------------
    const expectedNames = new Set(columns.map((c) => c.name));
    for (const actual of live) {
      if (!expectedNames.has(actual.name)) {
        items.push({
          severity: 'info',
          table,
          column: actual.name,
          kind: 'extra-column',
          detail:
            `Column "${table}"."${actual.name}" exists in the database but not in the schema. ` +
            `Harmless — Prisma lists its columns explicitly — but it will not be backed up by ` +
            `a schema-driven export.`
        });
      }
    }
  }

  // ---- Attach table DDL in dependency order ------------------------------
  for (const table of orderByDependency(missingTables, catalog)) {
    const ddl = catalog.tables.get(table);
    const item = items.find((i) => i.kind === 'missing-table' && i.table === table && i.severity === 'additive');
    if (ddl && item) item.sql = [ddl.createSql, ...ddl.indexSql];
  }

  const additive = items.filter((i) => i.severity === 'additive');
  const blocking = items.filter((i) => i.severity === 'blocking');

  // CREATE TABLE before ALTER TABLE: a column added to a table created in this
  // same pass would otherwise fail, and the ordering keeps the log readable.
  const tableCreates = additive.filter((i) => i.kind === 'missing-table');
  const columnAdds = additive.filter((i) => i.kind !== 'missing-table');
  const orderedCreates = orderByDependency(
    tableCreates.map((i) => i.table),
    catalog
  ).map((t) => tableCreates.find((i) => i.table === t)!);

  return {
    ok: additive.length === 0 && blocking.length === 0,
    repairable: blocking.length === 0 && additive.length > 0,
    items,
    additive,
    blocking,
    repairSql: [...orderedCreates, ...columnAdds].flatMap((i) => i.sql ?? []),
    ddlSource: catalog.root
  };
}

// ---------------------------------------------------------------------------
// Repair
// ---------------------------------------------------------------------------

export interface RepairResult {
  applied: string[];
  failed: { sql: string; error: string }[];
  /**
   * Rows whose foreign keys point at something that does not exist, found by
   * PRAGMA foreign_key_check after the DDL. Empty is the expected result:
   * creating a missing table cannot orphan a row, but if the database was
   * already damaged this is where it surfaces.
   */
  foreignKeyViolations: { table: string; rowid: number | null; parent: string }[];
}

/**
 * Apply the additive statements from a report.
 *
 * The caller is responsible for taking a backup first — see
 * `SchemaGuard.ensureCompatible()` and `scripts/repair-runtime-schema.ts`.
 *
 * Statements are applied one at a time rather than in a transaction, on
 * purpose: SQLite executes DDL transactionally per statement, and a partial
 * ALTER sequence is still a strictly better database than the one we started
 * with. Anything that fails is reported and the caller decides whether to
 * restore.
 */
export async function applyRepair(client: PrismaClient, report: DriftReport): Promise<RepairResult> {
  const applied: string[] = [];
  const failed: { sql: string; error: string }[] = [];

  // Foreign key enforcement is disabled for the duration of the DDL. Creating
  // ten tables that reference one another cannot be done in an order that
  // satisfies every constraint at every intermediate step, and SQLite would
  // reject the sequence. Integrity is re-checked explicitly below rather than
  // assumed — the check is the point, not the PRAGMA.
  let fkWasOn = true;
  try {
    const rows = await client.$queryRawUnsafe<{ foreign_keys: number }[]>('PRAGMA foreign_keys');
    fkWasOn = rows?.[0]?.foreign_keys !== 0;
    await client.$executeRawUnsafe('PRAGMA foreign_keys=OFF');
  } catch {
    // Some drivers report PRAGMA reads oddly; proceeding is still correct.
  }

  for (const sql of report.repairSql) {
    try {
      await client.$executeRawUnsafe(sql);
      applied.push(sql);
    } catch (err: unknown) {
      failed.push({ sql, error: err instanceof Error ? err.message : String(err) });
    }
  }

  let foreignKeyViolations: RepairResult['foreignKeyViolations'] = [];
  try {
    const rows = await client.$queryRawUnsafe<
      { table: string; rowid: number | null; parent: string }[]
    >('PRAGMA foreign_key_check');
    foreignKeyViolations = (rows ?? []).map((r) => ({
      table: r.table,
      rowid: r.rowid ?? null,
      parent: r.parent
    }));
  } catch {
    // Not fatal: the DDL either applied or it did not, and that is reported.
  }

  if (fkWasOn) {
    try {
      await client.$executeRawUnsafe('PRAGMA foreign_keys=ON');
    } catch {
      /* best effort */
    }
  }

  return { applied, failed, foreignKeyViolations };
}

/** Human-readable summary for logs and for the CLI. */
export function formatReport(report: DriftReport): string {
  if (report.ok) return 'Database schema matches the Prisma datamodel.';

  const lines: string[] = [];
  if (report.blocking.length) {
    lines.push(`BLOCKING (${report.blocking.length}) — manual migration required:`);
    for (const i of report.blocking) lines.push(`  x ${i.detail}`);
  }
  if (report.additive.length) {
    lines.push(`ADDITIVE (${report.additive.length}) — safe to apply automatically:`);
    for (const i of report.additive) lines.push(`  + ${i.detail}`);
  }
  const info = report.items.filter((i) => i.severity === 'info');
  if (info.length) {
    lines.push(`INFO (${info.length}) — no action needed:`);
    for (const i of info) lines.push(`  . ${i.detail}`);
  }
  if (report.additive.some((i) => i.kind === 'missing-table')) {
    lines.push(`Recorded DDL source: ${report.ddlSource ?? 'none'}`);
  }
  return lines.join('\n');
}
